#!/usr/bin/env php
<?php
define('PATH_ROOT', __DIR__);
define('PATH_VENDOR', PATH_ROOT . '/vendor');
define('PATH_BASE', PATH_ROOT . '/src');

require PATH_VENDOR . '/autoload.php';

define('YII_ENV', 'dev');
define('YII_DEBUG', true);

// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);

$config  = require PATH_VENDOR . '/mlaxwong/paw/bootstrap/console.php';
$app = Yii::createObject(\yii\helpers\ArrayHelper::merge($config, [
    'basePath' => PATH_ROOT,
    'aliases' => [
        '@paw/user'   => __DIR__ . DIRECTORY_SEPARATOR . 'src',
    ],
    'controllerMap' => [
        'migrate' => [
            'migrationNamespaces' => [
                "paw\user\migrations\db",
            ],
        ],
        'rbac-migrate' => [
            'migrationNamespaces' => [
                "paw\user\migrations\\rbac",
            ],
        ],
    ],
]));
$app->run();